account/urls.py
from django.urls import path
from . import views
from . import views


app_name='account'



urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.account_index, name='account_index'),
    path('cta/', views.contact_us, name="contact_us"),
    path('users/', views.getuser, name="get_user"),
    path("login/", views._login, name="login"),
    path('register', views.register, name="register"),
    path("logout/", views._logout, name="logout"),
    # path("getuser/<int:id_user>", views.getuser, name="getuser"),
    # path("getuser/<str:username>", views.getuser_by_username, name="getuser_by_username"),
    
]

product/urls.py
from django.urls import path
from . import views


app_name='product'



urlpatterns = [
    # path('', views.index_product, name='home'),
    path("product", views.product_index, name="product_index"),
    path("product/get/", views.get_product, name="get_product"),
    path("product/list/", views.list_product, name="list_product"),
]

account/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User


def home(req):
    template="home.html"
    return render(req, template)


def contact_us(req):
    template="contact_us.html"
    return render(req, template)


def account_index(req):
    template="account_index.html"
    return render(req, template)


def _login(req):
    if req.method == "POST":
        username = req.POST.get("username", False)
        password = req.POST.get("password", False)
        if False not in [username, password]:
            if req.user.is_authenticated:
                return redirect("/account")
            user = authenticate(req, username=username, password=password)
            if user:
                login(request=req, user=user)
                return redirect("/")
        return render(req, "login.html")
    else:
        if req.user.is_authenticated:
            return redirect("/account")
        template="login.html"
        return render(req, template)


def _logout(req):
    logout(req)
    # return redirect("/account/login")
    template="home.html"
    return render(req, template)


def register(req):
    if req.method == "POST":
        username = req.POST.get("username", False)
        password = req.POST.get("password", False)
        email = req.POST.get("email", False)
        if False not in [username, password, email]:
            user = User.objects.create_user(username, email, password)
            user.save()
        template="login.html"
        return render(req, template)
    else:
        template="register.html"
        return render(req, template)
    


def getuser(req):
    user = User.objects.all()
    template="get_user.html"
    return render(req, template, {"getUser": user})

# def getuser(req, id_user=None):
#     return HttpResponse("getuser" + str(id_user))


# def getuser_by_username(req, username=None):
#     return HttpResponse("getuser" + username)

product/views.py
from django.shortcuts import render
from django.http import HttpResponse



def product_index(req):
    template="product_index.html"
    return render(req, template)


def get_product(req):
    template="get_product.html"
    return render(req, template)


def list_product(req):
    template="list_product.html"
    return render(req, template)

account/templates/account_index.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>Profile</h1>
        <ul>
            {% if not user.is_authenticated %}
                <a href="{% url 'account:login' %}"><li>Login</li></a>
            {% endif %}
            <a href="{% url 'account:logout' %}"><li>Logout</li></a>
            <!-- <a href="/account/register"><li>Register</li></a> -->
            <a href="{% url 'account:home' %}"><li>Back</li></a>
        </ul>
    </div>
</section>
{% endblock content %}

account/templates/get_user.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>Users List</h1>
        <ul>
            {% for user in getUser %}
                <li>{{ user.username | title}}</li>
            {% endfor %}
            <a href="{% url 'account:home' %}"><li>Back</li></a>
        </ul>
    </div>
</section>
{% endblock content %}

account/templates/login.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>Login</h1>
        <form action="{% url 'account:login' %}" method="post">
            {% csrf_token %}
            <div>
                <label for="username">Username: </label>
                <input class="username-inpt" type="text" name="username" id="username" value="shayan" placeholder="Username">
                <!-- value="shayan" -->
            </div>
            <div>
                <label for="password">Password: </label>
                <input class="password-inpt" name="password" type="password" id="password" placeholder="Password">
            </div>
            <!-- <input type="submit" value="Login"> -->
            <button class="submit-btn" type="submit">Login</button>
            <button class="register-btn">
                <a href="{% url 'account:register' %}">Register</a>
            </button>
        </form>
    </div>
</section>
{% endblock content %}

account/templates/logout.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>Logout</h1>
        <ul>
            <a href="{% url 'account:home' %}"><li>Back</li></a>
        </ul>
    </div>
</section>
{% endblock content %}

account/templates/register.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>Register</h1>
        <form action="{% url 'account:register' %}" method="post">
            {% csrf_token %}
            <div>
                <label for="username">Username: </label>
                <input class="username-inpt" type="text" name="username" id="username" placeholder="Username">
            </div>
            <div>
                <label for="password">Password: </label>
                <input class="password-inpt" name="password" type="password" id="password" placeholder="Password">
            </div>
            <div>
                <label for="email">Email: </label>
                <input class="email-inpt" name="email" type="email" id="email" placeholder="Email">
            </div>
            <!-- <input type="submit" value="Login"> -->
            <button class="submit-btn" type="submit">Register</button>
            <button class="reset-btn" type="reset">Reset</button>
            <button class="login-btn"><a href="{% url 'account:login' %}">Login</a></button>
        </form>
</section>
{% endblock content %}

product/templates/get_product.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>Get Product</h1>
        <ul>
            <a href="{% url 'product:product_index' %}"><li>Back</li></a>
        </ul>
    </div>
</section>
{% endblock content %}

product/templates/list_product.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>List Product</h1>
        <ul>
            <a href="{% url 'product:product_index' %}"><li>Back</li></a>
        </ul>
    </div>
</section>
{% endblock content %}

product/templates/product_index.html
{% extends "base.html" %}

{% load static %}

        
{% block content %}
<section>
    <div class="mycard">
        <h1>PRODUCT</h1>
        <ul>
            <a href="{% url 'product:list_product' %}"><li>List Product</li></a>
            <a href="{% url 'product:get_product' %}"><li>Get Product</li></a>
            <a href="{% url 'account:home' %}"><li>Back</li></a>
        </ul>
    </div>
</section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static '/css/general.css' %}">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Shayan</title>
    </head>

    <body>
        <div class="topnav-l">
            <a href="{% url 'account:home' %}"><button class="home-button">
                <img class="home-color" src="{% static 'icons/home.svg' %}"/>
            </button>HOME</a> |  
            <a href="{% url 'account:contact_us' %}">CONTACT US</a>
        </div>
        <div class="topnav-r">
            {% if not request.user.is_authenticated %}
                <a href="{% url 'account:login' %}">LOGIN</a>
            {% else %}
                <a href="{% url 'account:account_index' %}">Hi {{ request.user | title}}</a> |
                <a href="{% url 'account:logout' %}">LOGOUT</a>
                <!-- <a href="/account">ACCOUNT</a> |
                <a href="/product">PRODUCT</a> | -->
            {% endif %} 
        </div>

        {% block content %}
        {% endblock content %}   

        <footer class="footer">
            <p class="footer-p">Shayan Ataei || 
                <a class="footer-a" href="https://github.com/shayan-ataei/home-page" target="_blank">
                    GitHub
                </a>
            </p>
        </footer>
    </body>

</html>

templates/contact_us.html
{% extends "base.html" %}

{% load static %}


{% block content %}
<section>
    <div class="mycard">
        <h1>Shayan Ataei</h1>
        <ul>
            <a href="https://github.com/shayan-ataei" target="_blank">
                <li><img class="github" src="{% static 'icons/github.svg' %}" alt=""> GitHub</li>
            </a>
            <a><li>Shayan.80.s8@gmail.com</li></a>
        </ul>
    </div>
</section>
{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% load static %}


{% block content %}
<section>
    <div class="mycard">
        <h1>WELCOME</h1>
        <ul>
            <!-- {% if not user.is_authenticated %}
                <a href="/account/login"><li>Login</li></a>
            {% endif %} -->
            {% if request.user.is_authenticated %}
                <a href="{% url 'account:account_index' %}"><li>Profile</li></a>
                <a href="{% url 'product:product_index' %}"><li>Product</li></a>
                <a href="{% url 'account:get_user' %}"><li>Users List</li></a>
                <!-- <a href="/account/logout"><li>Logout</li></a> -->
            {% else %}
                <p>Login First</p>
            {% endif %}
            
            
        </ul>
    </div>
</section>
{% endblock content %}